### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by CEDEssedi** [Flooding-against-Ransomware/ranflood#2]
HI

i tried to do my first install of ranflood on a windows server 2019 machine.

I was unable to run the daemon. In particular, I get this error:

_| [main] ERROR org.ranflood.daemon.RanFlood.main
| Expected 1 argument, path to the settings ini file._

I think I don't quite understand how to configure everything to run.

Do you have any pointers?

Thank you

**Comment by thesave** [comment]
Hi,

Thank you very much for trying out Ranflood and letting us know.

Did you follow the execution guideline from the README? [https://github.com/Flooding-against-Ransomware/ranflood#ranflood

**Comment by CEDEssedi** [comment]
HI,

I didn't realize that you had to start the daemon putting the path of the .ini file as an argument.

Now I managed to start the daemon. I do some tests, in case I have difficulties I will disturb you again.


Thanks a lot for the answer.

**Comment by thesave** [comment]
Perfect.
Please, keep in mind that Ranflood is still in its beta phase, so we do not recommend its usage in production but rather on non-essential, experimental nodes.
We hope you'll find the tool useful :)
